INSERT INTO concepto(
            id, nombre, cuenta_contable ,created_at ,codigo, descripcion, 
            activo, tipo,esimprimible ) 
VALUES
(-1,'Sueldo Básico',-46,current_timestamp, '' , '' , 1 , '',true ) , 
(-2,'Sueldo Anual Complementario',-46,current_timestamp, '' , '' , 1 , '',true ) , 
(-3,'Vacaciones',-46,current_timestamp, '' , '' , 1 , '',true ) , 
(-4,'Antiguedad',-46,current_timestamp, '' , '' , 1 , '',true ) , 
(-5,'Horas Extras 50%',-46,current_timestamp, '' , '' , 1 , '',true ) , 
(-6,'Horas Extras 100%',-46,current_timestamp, '' , '' , 1 , '',true ) , 
(-7,'Indemnización por Despido',-46,current_timestamp, '' , '' , 1 , '',true ) , 
(-8,'Preaviso',	-46,current_timestamp, '' , '' , 1 , '',true ) , 
(-9,'SAC sobre Preaviso',-46,current_timestamp, '' , '' , 1 , '',true ) , 
(-10,'SAC sobre Vacaciones No Gozadas',	-46,current_timestamp, '' , '' , 1 , '',true ) , 
(-11,'Vacaciones No Gozadas',-46,current_timestamp, '' , '' , 1 , '',true ) , 
(-12,'Gratificación',-46,current_timestamp, '' , '' , 1 , '',true ) , 
(-13,'Integración Mes de despido',-46,current_timestamp, '' , '' , 1 , '',true ) , 
(-14,'SAC sobre Int. Mes de despido',-46,current_timestamp, '' , '' , 1 , '',true ) , 
(-15,'Días Enfermedad',-46,current_timestamp, '' , '' , 1 , '',true ) , 
(-16,'Días Accidente',-46,current_timestamp, '' , '' , 1 , '',true ) , 
(-17,'Días Faltas injustificadas',-46,current_timestamp, '' , '' , 1 , '',true ) , 
(-18,'Jubilación',-48,current_timestamp, '' , '' , 1 , '',true ) , 
(-19,'Ley 19.032',-48,current_timestamp, '' , '' , 1 , '',true ) , 
(-20,'Obra Social',-48,current_timestamp, '' , '' , 1 , '',true ) ,
(-21,'Ley de Riesgos de Trabajo',-47,current_timestamp, '' , '' , 1 , '',false ) ,
(-22,'Seguro Colectivo de Vida',-47,current_timestamp, '' , '' , 1 , '',false ) ,
(-23,'Vales Alimentarios',-47,current_timestamp, '' , '' , 1 , '',false),
(-24,'Contribuciones RENATRE',-47,current_timestamp, '' , '' , 1 , '',false),
(-25,'Seguro Sepelio UATRE',-47,current_timestamp, '' , '' , 1 , '',false),
(-26,'Jubilación – Aportes Patronales',-47,current_timestamp, '' , '' , 1 , '',false),
(-27,'Ley 19,032 – Aportes Patronales',-47,current_timestamp, '' , '' , 1 , '',false),
(-28,'Obra Social – Aportes Patronales',-47,current_timestamp, '' , '' , 1 , '',false);